name: E2E tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Determine trigger source
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
              echo "trigger_source=PR" >> $GITHUB_ENV
              echo "trigger_message=<${{ github.event.pull_request.html_url }}|PR Link>" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "schedule" ]; then
              echo "trigger_source=Schedule" >> $GITHUB_ENV
              echo "trigger_message=Scheduled run" >> $GITHUB_ENV
          else
              echo "trigger_source=Other" >> $GITHUB_ENV
              echo "trigger_message=Other trigger" >> $GITHUB_ENV
          fi

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Restore Caches (Dependencies & Cypress)
        id: restore-caches
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-cypress-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cypress-
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Install dependencies (if cache is missing or outdated)
        run: yarn install --frozen-lockfile --prod

      - name: Create directories
        run: mkdir -p report/HTML report/JSON cypress/screenshots
      
      - name: Run Cypress tests
        id: cypress
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: yarn cypress:github

      - name: Generate HTML report
        if: ${{ always() && (steps.cypress.outcome == 'success' || steps.cypress.outcome == 'failure') }}
        run: |
          yarn report
          sleep 10
  
      - name: Upload HTML report as an artifact
        if: ${{ always() && (steps.cypress.outcome == 'success' || steps.cypress.outcome == 'failure') }}
        uses: actions/upload-artifact@v4
        with:
          name: "HTML Report"
          path: "report/HTML/cucumber_report.html"


      - name: Store dependencies cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Store Cypress cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-